### ISSUE TITLE
Koivisto 7.0 Release text

### ISSUE THREAD

**Issue by Luecx** [Luecx/Koivisto#155]
## Koivisto 7.0

With the next TCEC swiss cup nearing and a great performance at the previous TCEC event, we decided to release the next version of Koivisto. Since many people noticed the "unusual", non-crashing, performance of Koivisto at the previous TCEC cup, questions have been raised, asking how and why Koivisto is performing so well. 

The answer to that question is more complex than just a few sentences. A few people realized that Koivisto is not played with the normal network publicly available. With this release, we retrained another network of similar performance which will be embedded in the engine. Due to a huge amount of search patches, Koivisto 7.0 outperforms Koivisto 6.0 by a big margin with a win/loss ratio of over 6 and a stunning 110 Elo in self-play. We have not added major new features beside performance and accuracy.

We hope to further bring out more patches which will increase the strength even further. We plan to release major versions every 100 Elo in Self-Play which is a very ambitious goal from now on.

**Comment by altarchess** [comment]
Koivisto 7.0
Howdy fellow chess enthusiasts,

It's been a while since we released 6.0, but now it's finally time for another release. Just a few days ago we passed the usual 100 stc self-play elo we aim for for every release. Most of the gains come from search patches, although the embedded network is also significantly stronger.

Another reason we decided to release now is that we don't think we are going to be able to squeeze more elo out of our current network arch. So we wanted to release 7.0 as the last version off our simplistic arch,and then move on to more powerfull stuff.

Insert latest self play regression test here

Koivisto 7.0 will play in the upcomming TCEC swizz.

With love,
Finny & Kimmy
