### ISSUE TITLE
change log and specs

### ISSUE THREAD

**Issue by tissatussa** [Luecx/Koivisto#25]
hi ! 

thanks for this new engine !  v4(.1) seems much faster than v3(.13) !

do you have a change log ? What are the coding ideas and specifications ?  I see Andrew Grant is saluted but little info about this engine ..
and why does it lack MultiPV ? Is it by design ?

**Comment by altarchess** [comment]
Do you mean faster in terms of nps or in terms of time to depth? We fixed a bug related to lmr and went for more agressive lmr in 4.1, so it should reach higher depths faster (It should also be less accurate at a given depth). The commit history sort of acts as a changelog, altough we do also list all the major changes between version when we make a rnew release. Here are the main changes between 4.0 and 3.0:

    updated tt-usage.
    does forced moves immediately.
    added bishop pawn endgame relations evaluation term.
    retuned entire evaluation with a larger dataset.
        tuned mobility scores instead of computing them.
        tuned king safety scores instead of computing them.
    cleaned up the code and added comments.
    asymmetric piece square tables based on king-king relation.
    changed reduction/extension policy.
    improved general time management.
    fixed cyclic time management which leads to the engine using a lot more time in games with cyclic time controls.
    fixed speed-related issues.
    added a logo and banner.

We do not currently have MultiPV simply because we don't consider it a very important feature and it hasn't been close to the top of our to-do piles :P We are open to implementing it if people show interest tho.

**Comment by tissatussa** [comment]
I mean faster in terms of time to depth.

i frequently use MPV but i'm starting to learn about it .. it's used for analysis mode and i like it .. with other MPV engines i did tests with some positions where i might see a move getting a higher value after certain depth, but only when using MPV, otherwise that move would "no longer be considered" beyond some depth, so it seems .. I'm not into chess programming but use several UCI engines .. does the engine not have any second / third choice move ?

**Comment by altarchess** [comment]
Its faster in terms of time to depth because we made some changes to the [lmr reduction](https://www.chessprogramming.org/Late_Move_Reductions) logic. 

The engine does not have a 2nd/3rd move choice as it only tries to prove that other moves are worse than the 1st choice. It doesn't care about how much worse they are, only about the fact that they are worse. When doing MultiPV the engine also has to care about the scores of other moves, thus making it slower overall. Its a very useful analysis tool tho, so we'll definetly implement it.

**Comment by tissatussa** [comment]
i'm a programmer but not at chess engines .. i study some, tho .. but i guess you need some value to decide a move is "worse", so other moves than the 1st choice should have a value to compare, and so we have MPV !?

**Comment by altarchess** [comment]
We use [Alpha-Beta pruning](https://www.chessprogramming.org/Alpha-Beta), so we only know that the other moves are worse than alpha. But yeah, we are definetly going to implement MultiPV as it can be very useful in analysis
